---
- name: Converge
  hosts: all

  collections:
    - merative.spm_middleware

  roles:
    - iim

  vars:
    iim_agent_version: 1.9.1001.20191112_1525
    download_url: "{{ lookup('env','ARTIFACTORY_URL') }}/{{ lookup('env','ARTIFACTORY_REPO') }}/SoftwareInstallers"
    download_header: {'X-JFrog-Art-Api': "{{ lookup('env','ARTIFACTORY_TOKEN' )}}"}
